-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    acct_num INT NOT NULL,
    address VARCHAR(255) NOT NULL,
    balance INT NOT NULL
);

CREATE TABLE Seller (
    uid INT NOT NULL REFERENCES Users(id),
    balance INT NOT NULL
);

CREATE TABLE Inventory (
    sellerID INT NOT NULL,
    productname VARCHAR(255) NOT NULL,
    productID INT NOT NULL,
    quantity INT NOT NULL 
    PRIMARY KEY (sellerID, productID)
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    available BOOLEAN DEFAULT TRUE
);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE Carts (
    uid INT NOT NULL REFERENCES USERS(id),
    pid INT NOT NULL REFERENCE Products(id),
);
